# Generated by Django 4.1.5 on 2023-04-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_currency',
            field=models.CharField(blank=True, choices=[('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNH', 'Chinese Yuan'), ('EUR', 'Euro'), ('GBP', 'British Pound'), (
                'HKD', 'Hong Kong Dollar'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('USD', 'US Dollar')], default='USD', max_length=3, null=True),
        ),
    ]
