# Generated by Django 4.1.5 on 2023-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_default_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KofiPayment',
            fields=[
                ('message_id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('tier_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
