# Generated by Django 4.1.5 on 2023-04-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
