# Generated by Django 4.1.5 on 2023-08-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kofipayment_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kofipayment',
            old_name='message_id',
            new_name='kofi_transaction_id',
        ),
    ]
