# Generated by Django 4.1.5 on 2023-04-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='history',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
