# Generated by Django 4.1.5 on 2023-08-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_message_id_kofipayment_kofi_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_admin_override',
            field=models.BooleanField(default=False, help_text='Admin override to make the user premium arbitrarily.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_until_via_kofi',
            field=models.DateField(blank=True, help_text='Premium expiry date. If subscribed through Ko-fi, is the date when the Ko-fi subscription ends if not renewed.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_until_via_patreon',
            field=models.DateField(blank=True, help_text='Premium expiry date. If subscribed through Patreon, is the date when the Ko-fi subscription ends if not renewed.', null=True),
        ),
        migrations.AddField(
            model_name='kofipayment',
            name='amount',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='kofipayment',
            name='currency',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='kofipayment',
            name='from_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kofipayment',
            name='is_first_subscription_payment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='kofipayment',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='kofipayment',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kofipayment',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kofipayment',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='premium_until',
            field=models.DateField(blank=True, help_text='Premium expiry date. If subscribed through direct payment, such as Stripe, this is the date when the subscription ends if not renewed.', null=True),
        ),
        migrations.AlterField(
            model_name='kofipayment',
            name='tier_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
