# Generated by Django 4.1.5 on 2023-04-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
