# Generated by Django 4.1.5 on 2023-08-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_premium_admin_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kofipayment',
            name='amount',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='kofipayment',
            name='currency',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='kofipayment',
            name='from_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kofipayment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kofipayment',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kofipayment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
