# Generated by Django 4.1.5 on 2024-07-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_modulebomlistcomponentforitemrating_rating'),
        ('accounts', '0007_alter_kofipayment_amount_alter_kofipayment_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotes',
            name='user',
        ),
        migrations.AddField(
            model_name='usernotes',
            name='built_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='modules.builtmodules'),
        ),
        migrations.AddField(
            model_name='usernotes',
            name='want_to_build_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='modules.wanttobuildmodules'),
        ),
    ]
