# Generated by Django 4.1.5 on 2024-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_usernotes_user_usernotes_built_module_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usernotes',
            constraint=models.UniqueConstraint(fields=('want_to_build_module',), name='unique_want_to_build_module'),
        ),
        migrations.AddConstraint(
            model_name='usernotes',
            constraint=models.UniqueConstraint(fields=('built_module',), name='unique_built_module'),
        ),
    ]
