# Generated by Django 4.1.5 on 2023-06-19 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_until',
            field=models.DateField(blank=True, help_text='Premium expiry date. Is null if not premium or premium via Patreon.', null=True),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
