# Generated by Django 4.1.5 on 2023-06-23 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usernotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
