# Generated by Django 4.1.5 on 2024-10-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_alter_manufacturer_slug_alter_module_slug'),
        ('shopping_list', '0002_alter_usershoppinglistsaved_name'),
        ('accounts', '0009_usernotes_unique_want_to_build_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='user_shopping_list_saved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_user_shopping_list_saved', to='shopping_list.usershoppinglistsaved'),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='built_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_built', to='modules.builtmodules'),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='want_to_build_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_want_to_build', to='modules.wanttobuildmodules'),
        ),
        migrations.AddConstraint(
            model_name='usernotes',
            constraint=models.UniqueConstraint(fields=('user_shopping_list_saved',), name='unique_user_shopping_list_saved'),
        ),
    ]
