# Generated by Django 5.0 on 2024-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_usernotes_user_shopping_list_saved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotes",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
