# Generated by Django 4.1.5 on 2023-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_datetime_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='datetime_updated',
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_until',
            field=models.DateField(blank=True, help_text='Premium expiry date. Is null if not premium or premium via Patreon.', null=True),
        ),
    ]
