# Generated by Django 5.0 on 2024-11-22 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usernotes_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('KRW', 'South Korean Won'), ('SGD', 'Singapore Dollar'), ('NOK', 'Norwegian Krone'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
