# Generated by Django 5.0 on 2024-12-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_default_currency_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='cookie_consent_status',
            field=models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='deny', max_length=10),
        ),
    ]
