# Generated by Django 5.0 on 2024-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usernotes_cookie_consent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotes',
            name='cookie_consent_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cookie_consent_status',
            field=models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='deny', max_length=10),
        ),
    ]
