# Generated by Django 4.1.5 on 2024-07-19 04:03

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    replaces = [('pages', '0001_initial'), ('pages', '0002_rename_pages_page'), ('pages', '0003_staticpage'), ('pages', '0004_alter_staticpage_content'), ('pages', '0005_delete_page')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
            ],
        ),
    ]
