from django.urls import path
from api.views import (
    ModuleDetailView,
    get_user_inventory,
    get_user_history,
    get_user_me,
    get_built_modules,
    get_wtb_modules,
    get_module_bom_list_items,
    get_components,
    get_components_by_ids,
    get_user_inventory_quantity,
    user_inventory_quantity_add_or_create,
    user_inventory_update,
    get_user_shopping_list,
    user_anonymous_shopping_list_add_or_update,
    user_shopping_list_add_or_update,
    get_user_shopping_list_quantity_bom_item_agnostic,
    get_user_shopping_list_quantity,
    get_user_anonymous_shopping_list_quantity,
    get_user_inventory_quantities_for_bom_list_item,
    user_inventory_delete,
)

urlpatterns = [
    path("get-user-me/", get_user_me, name="user-me"),
    path("get-user-history/", get_user_history, name="user-history"),
    path("get-built-modules/", get_built_modules, name="get-built-modules"),
    path("get-wtb-modules/", get_wtb_modules, name="get-built-modules"),
    path("inventory/", get_user_inventory, name="user-inventory"),
    path(
        "inventory/bom-list-item/<int:modulebomlistitem_pk>/aggregate-sum/",
        get_user_inventory_quantities_for_bom_list_item,
        name="user-inventory-quantities-for-bom-list-item",
    ),
    path(
        "inventory/<int:component_pk>/component-quantity/",
        get_user_inventory_quantity,
        name="user-inventory-quantity",
    ),
    path(
        "inventory/<int:component_pk>/add-or-update/",
        user_inventory_quantity_add_or_create,
        name="user_inventory_add_or_update",
    ),
    path(
        "inventory/<int:component_pk>/update/",
        user_inventory_update,
        name="user_inventory_update",
    ),
    path(
        "inventory/<int:component_pk>/delete/",
        user_inventory_delete,
        name="user_inventory_delete",
    ),
    path("shopping_list/", get_user_shopping_list, name="user-shopping-list"),
    path(
        "shopping_list/<int:component_pk>/add-or-update/",
        user_shopping_list_add_or_update,
        name="user-shopping-list-add-or-update",
    ),
    path(
        "shopping_list/<int:component_pk>/anonymous-add-or-update/",
        user_anonymous_shopping_list_add_or_update,
        name="user-anonymous-shopping-list-add-or-update",
    ),
    path(
        "shopping_list/<int:component_pk>/component-quantity/",
        get_user_anonymous_shopping_list_quantity,
        name="user-shopping-list-anonymous",
    ),
    path(
        "shopping_list/<int:component_pk>/<int:module_pk>/component-quantity/",
        get_user_shopping_list_quantity_bom_item_agnostic,
        name="user-shopping-list-bom-item-agnostic",
    ),
    path(
        "shopping_list/<int:component_pk>/<int:modulebomlistitem_pk>/<int:module_pk>/component-quantity/",
        get_user_shopping_list_quantity,
        name="user-shopping-list",
    ),
    path("components/", get_components, name="component-list"),
    path("components/<str:pks>/", get_components_by_ids,
         name="component-list-by-ids"),
    path("module/<slug:slug>/", ModuleDetailView.as_view(), name="module-detail"),
    path(
        "module/<int:module_pk>/bom-list-items/",
        get_module_bom_list_items,
        name="module-bom-list-items",
    ),
]
