# Generated by Django 4.1.5 on 2023-03-22 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0005_alter_builtmodules_id_alter_modulebomlistitem_id_and_more'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileShoppingListData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.JSONField(blank=True, null=True)),
                ('bom_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modulebomlistitem')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Shopping List',
            },
        ),
    ]
