# Generated by Django 4.1.5 on 2023-07-13 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShoppingListSaved',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_saved', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bom_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.modulebomlistitem')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usernotes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Archived Shopping Lists',
            },
        ),
        migrations.CreateModel(
            name='UserShoppingList',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bom_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.modulebomlistitem')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Shopping List',
            },
        ),
        migrations.AddIndex(
            model_name='usershoppinglistsaved',
            index=models.Index(fields=['user'], name='shopping_li_user_id_96f7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglistsaved',
            index=models.Index(fields=['user', 'time_saved'], name='shopping_li_user_id_e421d8_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglistsaved',
            index=models.Index(fields=['time_saved', 'user'], name='shopping_li_time_sa_226df2_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglistsaved',
            index=models.Index(fields=['time_saved'], name='shopping_li_time_sa_a1ec8f_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglist',
            index=models.Index(fields=['user'], name='shopping_li_user_id_747579_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglist',
            index=models.Index(fields=['user', 'component'], name='shopping_li_user_id_b36416_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglist',
            index=models.Index(fields=['user', 'bom_item'], name='shopping_li_user_id_957f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglist',
            index=models.Index(fields=['user', 'module'], name='shopping_li_user_id_b765c0_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglist',
            index=models.Index(fields=['user', 'component', 'bom_item'], name='shopping_li_user_id_e1a44d_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglist',
            index=models.Index(fields=['user', 'component', 'bom_item', 'module'], name='shopping_li_user_id_0e78e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='usershoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'component', 'bom_item', 'module'), name='unique_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='usershoppinglist',
            constraint=models.UniqueConstraint(condition=models.Q(('bom_item', None), ('module', None)), fields=('user', 'component'), name='unique_without_optional'),
        ),
    ]
