# Generated by Django 4.1.5 on 2023-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershoppinglistsaved',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
