# Generated by Django 5.0 on 2024-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_list", "0003_alter_usershoppinglistsaved_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="usershoppinglist",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="usershoppinglistsaved",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
