# Generated by Django 4.1.5 on 2023-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_alter_usershoppinglist_module_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usershoppinglist',
            index=models.Index(fields=['user', 'bom_item'], name='shopping_li_user_id_957f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglist',
            index=models.Index(fields=['user', 'module'], name='shopping_li_user_id_b765c0_idx'),
        ),
    ]
