# Generated by Django 4.1.5 on 2023-04-20 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_modulebomlistcomponentforitemrating_modules_mod_user_id_f20e70_idx_and_more'),
        ('shopping_list', '0005_usershoppinglist_shopping_li_user_id_957f1d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershoppinglist',
            name='bom_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.modulebomlistitem'),
        ),
        migrations.AlterField(
            model_name='usershoppinglist',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.module'),
        ),
    ]
