# Generated by Django 4.1.5 on 2023-04-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0006_alter_usershoppinglist_bom_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usershoppinglist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usershoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'component', 'bom_item', 'module'), name='unique_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='usershoppinglist',
            constraint=models.UniqueConstraint(condition=models.Q(('bom_item', None), ('module', None)), fields=('user', 'component'), name='unique_without_optional'),
        ),
    ]
