# Generated by Django 4.1.5 on 2023-05-23 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0008_alter_usershoppinglist_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedLists',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lists', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Saved Shopping Lists',
            },
        ),
    ]
