# Generated by Django 4.1.5 on 2023-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0009_usersavedlists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersavedlists',
            options={'verbose_name_plural': 'User Archived Shopping Lists'},
        ),
        migrations.AddField(
            model_name='usersavedlists',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usershoppinglist',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
