# Generated by Django 4.1.5 on 2023-05-25 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_module_discontinued'),
        ('components', '0004_component_discontinued_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0010_alter_usersavedlists_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShoppingListSaved',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_saved', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bom_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.modulebomlistitem')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Archived Shopping Lists',
            },
        ),
        migrations.RemoveField(
            model_name='usershoppinglist',
            name='location',
        ),
        migrations.DeleteModel(
            name='UserSavedLists',
        ),
        migrations.AddIndex(
            model_name='usershoppinglistsaved',
            index=models.Index(fields=['user'], name='shopping_li_user_id_96f7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglistsaved',
            index=models.Index(fields=['user', 'time_saved'], name='shopping_li_user_id_e421d8_idx'),
        ),
        migrations.AddIndex(
            model_name='usershoppinglistsaved',
            index=models.Index(fields=['time_saved'], name='shopping_li_time_sa_a1ec8f_idx'),
        ),
    ]
