# Generated by Django 4.1.5 on 2023-05-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0011_usershoppinglistsaved_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usershoppinglistsaved',
            index=models.Index(fields=['time_saved', 'user'], name='shopping_li_time_sa_226df2_idx'),
        ),
    ]
