# Generated by Django 4.1.5 on 2023-06-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usernotes'),
        ('shopping_list', '0012_usershoppinglistsaved_shopping_li_time_sa_226df2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershoppinglistsaved',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usernotes'),
        ),
    ]
