# Generated by Django 4.1.5 on 2023-06-21 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0013_alter_usershoppinglistsaved_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershoppinglist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='usershoppinglistsaved',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
