# Generated by Django 4.1.5 on 2023-06-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0015_remove_usershoppinglist_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershoppinglist',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usershoppinglistsaved',
            old_name='uuid',
            new_name='id',
        ),
    ]
