# Generated by Django 4.1.5 on 2023-07-13 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1', max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='module_imgs')),
                ('image_jpeg', models.ImageField(blank=True, upload_to='module_imgs_jpeg')),
                ('manufacturer_page_link', models.URLField(blank=True)),
                ('bom_link', models.URLField(blank=True)),
                ('manual_link', models.URLField(blank=True)),
                ('modulargrid_link', models.URLField(blank=True)),
                ('mounting_style', models.CharField(blank=True, choices=[('smt', 'Surface Mount (SMT)'), ('th', 'Through Hole')], max_length=50, null=True)),
                ('discontinued', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modules.manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='WantToBuildModules',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Want-to-Build Modules',
            },
        ),
        migrations.CreateModel(
            name='ModuleBomListItem',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('designators', models.CharField(blank=True, help_text='A list of locations on the circuit board.', max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('components_options', models.ManyToManyField(related_name='component_identity_to_component', to='components.component')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modules.module')),
            ],
            options={
                'verbose_name_plural': 'Module BOM List Items',
            },
        ),
        migrations.CreateModel(
            name='ModuleBomListComponentForItemRating',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('module_bom_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modulebomlistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuiltModules',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Built Modules',
            },
        ),
        migrations.AddIndex(
            model_name='wanttobuildmodules',
            index=models.Index(fields=['user'], name='modules_wan_user_id_3e748a_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistitem',
            index=models.Index(fields=['module'], name='modules_mod_module__32b588_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistcomponentforitemrating',
            index=models.Index(fields=['user'], name='modules_mod_user_id_f20e70_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistcomponentforitemrating',
            index=models.Index(fields=['component'], name='modules_mod_compone_3cc59a_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistcomponentforitemrating',
            index=models.Index(fields=['module_bom_list_item'], name='modules_mod_module__f77570_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistcomponentforitemrating',
            index=models.Index(fields=['user', 'component', 'module_bom_list_item'], name='modules_mod_user_id_02eb64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulebomlistcomponentforitemrating',
            unique_together={('module_bom_list_item', 'component', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'manufacturer', 'version')},
        ),
        migrations.AddIndex(
            model_name='builtmodules',
            index=models.Index(fields=['user'], name='modules_bui_user_id_562371_idx'),
        ),
    ]
