# Generated by Django 4.1.5 on 2023-02-26 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1', max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('manufacturer_page_link', models.URLField(blank=True)),
                ('bom_link', models.URLField(blank=True)),
                ('manual_link', models.URLField(blank=True)),
                ('modulargrid_link', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modules.manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'unique_together': {('name', 'manufacturer', 'version')},
            },
        ),
    ]
