# Generated by Django 4.1.5 on 2023-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_farads_unit_and_more'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='mounting_style',
            field=models.CharField(blank=True, choices=[('smt', 'Surface Mount (SMT)'), ('th', 'Through Hole')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modulebomlistitem',
            name='components_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='component_identity_to_component', to='components.component'),
        ),
        migrations.AlterField(
            model_name='modulebomlistitem',
            name='designators',
            field=models.CharField(blank=True, default='', help_text='A list of locations on the circuit board.', max_length=255),
            preserve_default=False,
        ),
    ]
