# Generated by Django 4.1.5 on 2023-07-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_farads_unit_and_more'),
        ('modules', '0002_alter_module_mounting_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulebomlistitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.types'),
        ),
    ]
