# Generated by Django 4.1.5 on 2023-03-22 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('modules', '0003_wanttobuildmodules_builtmodules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleBomListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('designators', models.CharField(blank=True, help_text='A list of locations on the circuit board.', max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('components_options', models.ManyToManyField(related_name='component_identity_to_component', to='components.component')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modules.module')),
            ],
            options={
                'verbose_name_plural': 'Module BOM List Items',
                'unique_together': {('description', 'module')},
            },
        ),
    ]
