# Generated by Django 4.1.5 on 2023-07-27 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_modulebomlistitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcbVersion',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='1', max_length=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modules.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modulebomlistitem',
            name='pcb_version',
            field=models.ManyToManyField(blank=True, null=True, related_name='pcb_version', to='modules.pcbversion'),
        ),
    ]
