# Generated by Django 4.1.5 on 2023-03-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_modulebomlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtmodules',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulebomlistitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wanttobuildmodules',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
