# Generated by Django 4.1.5 on 2023-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_pcbversion_modulebomlistitem_pcb_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbversion',
            name='version',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
