# Generated by Django 4.1.5 on 2023-04-05 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0005_alter_builtmodules_id_alter_modulebomlistitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleBomListItemRating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component')),
                ('module_bom_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modulebomlistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('module_bom_list_item', 'component', 'user')},
            },
        ),
    ]
