# Generated by Django 4.1.5 on 2023-04-05 01:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0001_initial'),
        ('modules', '0006_modulebomlistitemrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleBomListItemRating',
            new_name='ModuleBomListComponentForItemRating',
        ),
    ]
