# Generated by Django 4.1.5 on 2023-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_modulebomlistitem_pcb_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbversion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
