# Generated by Django 4.1.5 on 2024-07-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_pcbversion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
