# Generated by Django 4.1.5 on 2023-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_rename_modulebomlistitemrating_modulebomlistcomponentforitemrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulebomlistitem',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='builtmodules',
            index=models.Index(fields=['user'], name='modules_bui_user_id_562371_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistitem',
            index=models.Index(fields=['module'], name='modules_mod_module__32b588_idx'),
        ),
        migrations.AddIndex(
            model_name='wanttobuildmodules',
            index=models.Index(fields=['user'], name='modules_wan_user_id_3e748a_idx'),
        ),
    ]
