# Generated by Django 4.1.5 on 2023-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_alter_modulebomlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='modulebomlistcomponentforitemrating',
            index=models.Index(fields=['user'], name='modules_mod_user_id_f20e70_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistcomponentforitemrating',
            index=models.Index(fields=['component'], name='modules_mod_compone_3cc59a_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistcomponentforitemrating',
            index=models.Index(fields=['module_bom_list_item'], name='modules_mod_module__f77570_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebomlistcomponentforitemrating',
            index=models.Index(fields=['user', 'component', 'module_bom_list_item'], name='modules_mod_user_id_02eb64_idx'),
        ),
    ]
