# Generated by Django 4.1.5 on 2024-07-08 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_module_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulebomlistcomponentforitemrating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
