# Generated by Django 4.1.5 on 2024-08-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_allow_comments'),
        ('modules', '0009_alter_modulebomlistcomponentforitemrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulebomlistitem',
            name='components_options',
            field=models.ManyToManyField(blank=True, related_name='component_identity_to_component', to='components.component'),
        ),
    ]
