# Generated by Django 4.1.5 on 2023-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_modulebomlistcomponentforitemrating_modules_mod_user_id_f20e70_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='component_type',
            field=models.CharField(blank=True, choices=[('smt', 'Surface Mount (SMT)'), ('th', 'Through Hole')], max_length=50, null=True),
        ),
    ]
