# Generated by Django 4.1.5 on 2023-05-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_module_component_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='component_type',
            new_name='mounting_style',
        ),
    ]
