# Generated by Django 4.1.5 on 2024-08-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0010_alter_modulebomlistitem_components_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="large_image_jpeg",
            field=models.ImageField(blank=True, upload_to="module_imgs_large_jpeg"),
        ),
        migrations.AddField(
            model_name="module",
            name="large_image_webp",
            field=models.ImageField(blank=True, upload_to="module_imgs_large_webp"),
        ),
        migrations.AddField(
            model_name="module",
            name="thumb_image_jpeg",
            field=models.ImageField(blank=True, upload_to="module_imgs_thumb_jpeg"),
        ),
        migrations.AddField(
            model_name="module",
            name="thumb_image_webp",
            field=models.ImageField(blank=True, upload_to="module_imgs_thumb_webp"),
        ),
    ]
