# Generated by Django 4.1.5 on 2023-05-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_rename_component_type_module_mounting_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
