# Generated by Django 4.1.5 on 2023-05-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_manufacturer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image_jpeg',
            field=models.ImageField(blank=True, upload_to='module_imgs_jpeg'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, upload_to='module_imgs'),
        ),
    ]
