# Generated by Django 4.1.5 on 2024-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_remove_module_image_jpeg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name_plural': 'Manufacturer'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
