# Generated by Django 4.1.5 on 2023-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_module_image_jpeg_alter_module_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='module',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='builtmodules',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modulebomlistcomponentforitemrating',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modulebomlistitem',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wanttobuildmodules',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
