# Generated by Django 5.0 on 2024-11-05 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_alter_manufacturer_slug_alter_module_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(blank=True, choices=[('Eurorack', 'Eurorack'), ('Pedals', 'Pedals'), ('Serge', 'Serge')], help_text='Select the module category (e.g., Eurorack, Pedals, Serge).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='hp',
            field=models.IntegerField(blank=True, help_text='Specify the width in HP (optional).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='module',
            name='rack_unit',
            field=models.CharField(blank=True, choices=[('3U', '3U'), ('4U', '4U'), ('5U', '5U')], help_text='Choose the rack unit (e.g., 3U, 4U, 5U).', max_length=2, null=True),
        ),
    ]
