# Generated by Django 5.0 on 2024-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_module_category_module_hp_module_rack_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebomlistitem',
            name='bom_specifies_a_choice_of_values',
            field=models.BooleanField(default=False, help_text='Check the BOM to select a value based on user preference.'),
        ),
    ]
