# Generated by Django 4.1.5 on 2023-06-21 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_builtmodules_uuid_manufacturer_uuid_module_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builtmodules',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.RemoveField(
            model_name='modulebomlistcomponentforitemrating',
            name='id',
        ),
        migrations.RemoveField(
            model_name='modulebomlistitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wanttobuildmodules',
            name='id',
        ),
        migrations.AlterField(
            model_name='builtmodules',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulebomlistcomponentforitemrating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modulebomlistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wanttobuildmodules',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
