# Generated by Django 4.1.5 on 2023-06-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0017_remove_builtmodules_id_remove_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builtmodules',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='modulebomlistcomponentforitemrating',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='modulebomlistitem',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wanttobuildmodules',
            old_name='uuid',
            new_name='id',
        ),
    ]
