# Generated by Django 5.0 on 2024-11-12 05:51
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0017_module_bom_under_construction"),
    ]

    operations = [
        TrigramExtension(),
    ]
