# Generated by Django 5.0 on 2024-11-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0018_auto_20241112_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebomlistitem',
            name='optional',
            field=models.BooleanField(default=False),
        ),
    ]
