# Generated by Django 5.0 on 2024-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0019_modulebomlistitem_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="builtmodules",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="modulebomlistcomponentforitemrating",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="modulebomlistitem",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pcbversion",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="wanttobuildmodules",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
