# Generated by Django 5.0 on 2024-11-21 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_rename_forward_current_avg_rectified_component_max_forward_current_and_more'),
        ('modules', '0020_builtmodules_date_created_manufacturer_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_component_description', models.CharField(help_text="Description of the original component (e.g., '100k resistor').", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the substitution.')),
                ('confirmed_by_manufacturer', models.BooleanField(default=False, help_text='Indicates whether the substitution is confirmed by the manufacturer.')),
                ('module_bom_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='modules.modulebomlistitem')),
                ('substitute_components', models.ManyToManyField(help_text='List of substitute components for the original component.', related_name='substitute_in_substitutions', to='components.component')),
            ],
            options={
                'verbose_name_plural': 'Substitutions',
            },
        ),
    ]
