# Generated by Django 5.0 on 2024-11-27 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0022_component_submitted_by_and_more'),
        ('modules', '0021_substitution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedComponentForBomListItem',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the suggested component.', max_length=10)),
                ('module_bom_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_component_bom_list_items', to='modules.modulebomlistitem')),
                ('suggested_by', models.ForeignKey(blank=True, help_text='User who suggested this component.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suggested_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_component_for_bom_list_items', to='components.component')),
            ],
            options={
                'verbose_name': 'Suggested Component for BOM List Item',
                'verbose_name_plural': 'Suggested Components for BOM List Item',
            },
        ),
    ]
