# Generated by Django 5.0 on 2024-12-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0022_suggestedcomponentforbomlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='rack_unit',
            field=models.CharField(blank=True, choices=[('1U', '1U'), ('3U', '3U'), ('4U', '4U'), ('5U', '5U')], help_text='Choose the rack unit (e.g., 3U, 4U, 5U).', max_length=2, null=True),
        ),
    ]
