# Generated by Django 5.0 on 2025-02-13 06:37

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0023_alter_module_rack_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='cost_built',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_built_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar (A$)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('CNY', 'Chinese Yuan (¥)'), ('EUR', 'Euro (€)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('INR', 'Indian Rupee (₹)'), ('JPY', 'Japanese Yen (¥)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('NOK', 'Norwegian Krone (kr)'), ('SGD', 'Singapore Dollar (S$)'), ('KRW', 'South Korean Won (₩)'), ('SEK', 'Swedish Krona (kr)'), ('CHF', 'Swiss Franc (Fr.)'), ('USD', 'US Dollar ($)')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_kit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_kit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar (A$)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('CNY', 'Chinese Yuan (¥)'), ('EUR', 'Euro (€)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('INR', 'Indian Rupee (₹)'), ('JPY', 'Japanese Yen (¥)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('NOK', 'Norwegian Krone (kr)'), ('SGD', 'Singapore Dollar (S$)'), ('KRW', 'South Korean Won (₩)'), ('SEK', 'Swedish Krona (kr)'), ('CHF', 'Swiss Franc (Fr.)'), ('USD', 'US Dollar ($)')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_partial_kit',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_partial_kit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar (A$)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('CNY', 'Chinese Yuan (¥)'), ('EUR', 'Euro (€)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('INR', 'Indian Rupee (₹)'), ('JPY', 'Japanese Yen (¥)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('NOK', 'Norwegian Krone (kr)'), ('SGD', 'Singapore Dollar (S$)'), ('KRW', 'South Korean Won (₩)'), ('SEK', 'Swedish Krona (kr)'), ('CHF', 'Swiss Franc (Fr.)'), ('USD', 'US Dollar ($)')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_pcb_only',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_pcb_only_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar (A$)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('CNY', 'Chinese Yuan (¥)'), ('EUR', 'Euro (€)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('INR', 'Indian Rupee (₹)'), ('JPY', 'Japanese Yen (¥)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('NOK', 'Norwegian Krone (kr)'), ('SGD', 'Singapore Dollar (S$)'), ('KRW', 'South Korean Won (₩)'), ('SEK', 'Swedish Krona (kr)'), ('CHF', 'Swiss Franc (Fr.)'), ('USD', 'US Dollar ($)')], default='USD', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_pcb_plus_front',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_pcb_plus_front_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar (A$)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('CNY', 'Chinese Yuan (¥)'), ('EUR', 'Euro (€)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('INR', 'Indian Rupee (₹)'), ('JPY', 'Japanese Yen (¥)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('NOK', 'Norwegian Krone (kr)'), ('SGD', 'Singapore Dollar (S$)'), ('KRW', 'South Korean Won (₩)'), ('SEK', 'Swedish Krona (kr)'), ('CHF', 'Swiss Franc (Fr.)'), ('USD', 'US Dollar ($)')], default='USD', editable=False, max_length=3, null=True),
        ),
    ]
