# Generated by Django 5.0 on 2025-02-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0024_module_cost_built_module_cost_built_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='cost_built_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_built_third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_kit_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_kit_third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_partial_kit_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_partial_kit_third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_pcb_only_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_pcb_only_third_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_pcb_plus_front_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cost_pcb_plus_front_third_party',
            field=models.BooleanField(default=False),
        ),
    ]
