# Generated by Django 5.0 on 2025-01-16 04:29

import django.db.models.deletion
import django_editorjs_fields.fields
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent category for this category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='post_imgs')),
                ('thumb_image_webp', models.ImageField(blank=True, null=True, upload_to='post_imgs_thumb_webp')),
                ('thumb_image_jpeg', models.ImageField(blank=True, null=True, upload_to='post_imgs_thumb_jpeg')),
                ('large_image_webp', models.ImageField(blank=True, null=True, upload_to='post_imgs_large_webp')),
                ('large_image_jpeg', models.ImageField(blank=True, null=True, upload_to='post_imgs_large_jpeg')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO meta keywords', max_length=255)),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('categories', models.ManyToManyField(blank=True, help_text='Select categories for this post.', related_name='blog_posts', to='blog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
