# Generated by Django 5.0 on 2025-01-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
