# Generated by Django 4.1.5 on 2023-12-03 20:50

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userinventory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location'], name='inventory_u_locatio_fccab0_gin'),
        ),
    ]
