# Generated by Django 4.1.5 on 2023-04-14 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinventory',
            unique_together={('user', 'component')},
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user'], name='inventory_u_user_id_446a44_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user', 'component'], name='inventory_u_user_id_d9ce30_idx'),
        ),
    ]
