# Generated by Django 4.1.5 on 2023-12-03 21:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_farads_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_userinventory_inventory_u_locatio_fccab0_gin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinventory',
            unique_together={('user', 'component', 'location')},
        ),
    ]
