# Generated by Django 4.1.5 on 2023-04-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_userinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='old_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinventory',
            name='old_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
