# Generated by Django 4.1.5 on 2023-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_userinventory_old_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
