# Generated by Django 5.0 on 2024-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_userinventory_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinventory",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
