# Generated by Django 4.1.5 on 2023-06-21 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_userinventory_datetime_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
