# Generated by Django 4.1.5 on 2023-06-21 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_userinventory_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
