# Generated by Django 4.1.5 on 2023-05-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mounting_style',
            field=models.CharField(blank=True, choices=[('smt', 'Surface Mount (SMT)'), ('th', 'Through Hole')], max_length=50, null=True),
        ),
    ]
