# Generated by Django 4.1.5 on 2023-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='farads_unit',
            field=models.CharField(blank=True, choices=[('mF', 'mF'), ('μF', 'μF'), ('nF', 'nF'), ('pF', 'pF')], default='', help_text='If the component type involves capacitance, this value MUST be set.', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='mounting_style',
            field=models.CharField(blank=True, choices=[('smt', 'Surface Mount (SMT)'), ('th', 'Through Hole')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='ohms_unit',
            field=models.CharField(blank=True, choices=[('Ω', 'Ω'), ('kΩ', 'kΩ'), ('MΩ', 'MΩ')], default='', help_text='If the component type involves resistance, this value MUST be set.', max_length=2),
            preserve_default=False,
        ),
    ]
