# Generated by Django 4.1.5 on 2023-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_mounting_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='types',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='component',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='componentmanufacturer',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='componentsupplier',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='types',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
