# Generated by Django 4.1.5 on 2024-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_farads_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
