# Generated by Django 4.1.5 on 2024-08-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='current_rating',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='component',
            name='forward_current',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The maximum forward current of the component.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='forward_current_avg_rectified',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The average forward current over a full cycle of an AC signal.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='forward_surge_current',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The maximum forward surge current of the component.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='forward_voltage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The forward voltage drop of the component.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='tolerance',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='component',
            name='voltage_rating',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
