# Generated by Django 4.1.5 on 2024-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_component_current_rating_component_forward_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='supplier_has_no_item_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='supplier_item_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
