# Generated by Django 4.1.5 on 2024-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_component_supplier_has_no_item_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='supplier_item_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
