# Generated by Django 4.1.5 on 2023-06-21 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_component_uuid_componentmanufacturer_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='id',
        ),
        migrations.RemoveField(
            model_name='componentmanufacturer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='componentsupplier',
            name='id',
        ),
        migrations.RemoveField(
            model_name='types',
            name='id',
        ),
        migrations.AlterField(
            model_name='component',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='componentmanufacturer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='componentsupplier',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='types',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
