# Generated by Django 4.1.5 on 2024-08-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_alter_component_supplier_item_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='supplier_item_no',
            field=models.CharField(blank=True, help_text="This must be set unless 'supplier_has_no_item_no' is checked.", max_length=100, null=True, unique=True),
        ),
    ]
