# Generated by Django 5.0 on 2024-11-05 22:12

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_alter_component_forward_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='unit_price',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '/', models.F('pcs')), output_field=models.DecimalField(decimal_places=2, max_digits=8)),
        ),
    ]
