# Generated by Django 5.0 on 2024-11-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_component_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='user_submission_hold',
            field=models.BooleanField(default=False),
        ),
    ]
