# Generated by Django 5.0 on 2024-11-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_componentsupplieritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='manufacturer_link',
            field=models.URLField(blank=True),
        ),
    ]
