# Generated by Django 5.0 on 2024-11-17 21:25

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_component_manufacturer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the size standard (e.g., 0805, SOIC14).', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the size standard.')),
                ('type', models.CharField(blank=True, choices=[('SMD', 'Surface-mount'), ('TH', 'Through-hole'), ('IC', 'IC Package')], help_text='Type of the component size standard (e.g., Surface-mount, Through-hole, IC Package).', max_length=20)),
                ('lead_spacing', models.DecimalField(blank=True, decimal_places=2, help_text='Lead spacing in mm for through-hole components. Must be greater than 0.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Size Standard',
                'verbose_name_plural': 'Size Standards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent category for this category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='components.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Category to which this component belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='components.category'),
        ),
        migrations.AddField(
            model_name='component',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Size standard for the component.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='components.sizestandard'),
        ),
    ]
