# Generated by Django 5.0 on 2024-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_remove_sizestandard_lead_spacing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='component',
            name='wattage',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='component',
            name='current_rating',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='component',
            name='forward_current',
            field=models.CharField(blank=True, help_text='The maximum forward current of the component.', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='forward_current_avg_rectified',
            field=models.CharField(blank=True, help_text='The average forward current over a full cycle of an AC signal.', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='forward_surge_current',
            field=models.CharField(blank=True, help_text='The maximum forward surge current of the component.', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='forward_voltage',
            field=models.CharField(blank=True, help_text='The forward voltage drop of the component.', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='tolerance',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='voltage_rating',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
