# Generated by Django 5.0 on 2024-11-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0018_alter_component_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='forward_current_avg_rectified',
            new_name='max_forward_current',
        ),
        migrations.RemoveField(
            model_name='component',
            name='forward_current',
        ),
        migrations.RemoveField(
            model_name='component',
            name='forward_surge_current',
        ),
    ]
