# Generated by Django 5.0 on 2024-11-22 06:52

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "components",
            "0019_rename_forward_current_avg_rectified_component_max_forward_current_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="componentsupplieritem",
            name="unit_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("price"), "/", models.F("pcs")
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=8),
            ),
        ),
    ]
