# Generated by Django 5.0 on 2024-11-22 17:04

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_componentsupplieritem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='user_submission_hold',
        ),
        migrations.AlterField(
            model_name='component',
            name='link',
            field=models.URLField(help_text='Deprecated'),
        ),
        migrations.AlterField(
            model_name='component',
            name='pcs',
            field=models.IntegerField(default=1, help_text='Deprecated - The number of component that are purchased per price (if they are sold in a set). Defaults to 1.'),
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', help_text='Deprecated', max_digits=4),
        ),
        migrations.AlterField(
            model_name='component',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Deprecated', null=True, on_delete=django.db.models.deletion.PROTECT, to='components.componentsupplier'),
        ),
        migrations.AlterField(
            model_name='component',
            name='supplier_has_no_item_no',
            field=models.BooleanField(default=False, help_text='Deprecated'),
        ),
        migrations.AlterField(
            model_name='component',
            name='supplier_item_no',
            field=models.CharField(blank=True, help_text="Deprecated - This must be set unless 'supplier_has_no_item_no' is checked.", max_length=100, null=True, unique=True),
        ),
    ]
