# Generated by Django 5.0 on 2024-11-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0022_component_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='current_rating',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='voltage_rating',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='wattage',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
