# Generated by Django 5.0 on 2024-11-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0023_alter_component_current_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='link',
            field=models.URLField(blank=True, help_text='Deprecated'),
        ),
    ]
