# Generated by Django 5.0 on 2024-12-08 19:36

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0025_componentsupplieritem_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='ditor_content',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
    ]
