# Generated by Django 5.0 on 2024-12-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0026_component_ditor_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='ditor_content',
            new_name='editor_content',
        ),
    ]
