# Generated by Django 5.0 on 2024-12-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0027_rename_ditor_content_component_editor_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='farads',
            field=models.FloatField(blank=True, help_text='If the component type involves capacitance, this value MUST be set.', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='ohms',
            field=models.FloatField(blank=True, help_text='If the component type involves resistance, this value MUST be set.', null=True),
        ),
    ]
