# Generated by Django 5.0 on 2024-12-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0028_alter_component_farads_alter_component_ohms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="pcs",
        ),
        migrations.RemoveField(
            model_name="component",
            name="price",
        ),
        migrations.RemoveField(
            model_name="component",
            name="price_currency",
        ),
        migrations.RemoveField(
            model_name="component",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="component",
            name="supplier_has_no_item_no",
        ),
        migrations.RemoveField(
            model_name="component",
            name="supplier_item_no",
        ),
    ]
