# Generated by Django 5.0 on 2024-12-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0029_remove_component_pcs_remove_component_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentsupplieritem',
            unique_together={('component', 'supplier'), ('supplier', 'supplier_item_no')},
        ),
    ]
