# Generated by Django 5.0 on 2024-12-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0030_alter_componentsupplieritem_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="link",
        )
    ]
