# Generated by Django 5.0 on 2025-01-16 04:29

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0031_remove_component_link_remove_component_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentsupplieritem",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar (A$)"),
                    ("GBP", "British Pound (£)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("CNY", "Chinese Yuan (¥)"),
                    ("EUR", "Euro (€)"),
                    ("HKD", "Hong Kong Dollar (HK$)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("NZD", "New Zealand Dollar (NZ$)"),
                    ("NOK", "Norwegian Krone (kr)"),
                    ("SGD", "Singapore Dollar (S$)"),
                    ("KRW", "South Korean Won (₩)"),
                    ("SEK", "Swedish Krona (kr)"),
                    ("CHF", "Swiss Franc (Fr.)"),
                    ("USD", "US Dollar ($)"),
                ],
                default="USD",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
