# Generated by Django 5.0 on 2025-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0032_remove_component_unit_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="pot_angle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Straight", "Straight"),
                    ("Right-Angle", "Right-Angle"),
                    ("Right-Angle-Long", "Right-Angle-Long"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_base_width",
            field=models.CharField(
                blank=True,
                help_text="Potentiometer base width (e.g., '9mm', '16mm', '24mm').",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_gangs",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of gangs (e.g., Single, Dual)"
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_mounting_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PCB Mount", "PCB Mount"),
                    ("Panel Mount", "Panel Mount"),
                    ("Solder Lug", "Solder Lug"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_shaft_diameter",
            field=models.CharField(
                blank=True,
                help_text="Shaft diameter (e.g., '6mm' or '1/4in.')",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_shaft_length",
            field=models.CharField(
                blank=True,
                help_text="Shaft length (e.g., '15mm' or '0.75in.')",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_shaft_material",
            field=models.CharField(
                blank=True,
                choices=[("Plastic", "Plastic"), ("Metal", "Metal")],
                help_text="Material of the shaft (Plastic or Metal).",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_shaft_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Smooth", "Smooth"),
                    ("Knurled", "Knurled"),
                    ("D-Shaft", "D-Shaft"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_split_shaft",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the shaft is split (adjustable width).",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="pot_taper",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Linear", "Linear (B)"),
                    ("Logarithmic", "Logarithmic (A)"),
                    ("Reverse Logarithmic", "Reverse Logarithmic (C)"),
                    ("Custom", "Custom (S, W, etc.)"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
