# Generated by Django 5.0 on 2025-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "components",
            "0033_remove_component_unit_price_component_pot_angle_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="component_height",
            field=models.CharField(
                blank=True,
                help_text="Component height (e.g., '5mm', '10mm').",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="footprint_length",
            field=models.CharField(
                blank=True,
                help_text="Capacitor footprint length (e.g., '5mm', '10mm').",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="footprint_width",
            field=models.CharField(
                blank=True,
                help_text="Capacitor footprint width (e.g., '5mm', '10mm').",
                max_length=10,
                null=True,
            ),
        ),
    ]
