# Generated by Django 4.1.5 on 2024-07-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0008_auto_20200920_2037'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customxtdcomment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_comments_xtd.xtdcomment'),
        ),
    ]
