# Generated by Django 4.1.5 on 2024-08-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_customxtdcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customxtdcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
