# Generated by Django 4.1.5 on 2023-03-08 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
